# Generated by Django 6.0.2 on 2026-02-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_genre_contentgenre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='genre',
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='contents', to='content_app.genre'),
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show'), ('series', 'Series')], default='movie', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ContentGenre',
        ),
    ]
